/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    NavbarTop: typeof import('./src/components/NavbarTop.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
